M48
; DRILL file {KiCad 7.0.10-7.0.10~ubuntu22.04.1} date 2024年02月03日 23時22分01秒
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-02-03T23:22:01+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10-7.0.10~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0394
%
G90
G05
T1
X6.7456Y-2.7661
X6.7456Y-2.9937
T2
X6.7022Y-3.4931
X6.7022Y-3.69
M30
