M48
; DRILL file {KiCad 7.0.2} date Mon Aug  7 19:48:14 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-08-07T19:48:14+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0394
%
G90
G05
T1
X6.7551Y-3.3463
X6.7551Y-3.5739
T2
X4.7878Y-2.9016
X4.7878Y-3.0984
T0
M30
